### ISSUE TITLE
Group Level Security Dashboards Not Supported

### ISSUE THREAD

**Issue by nikmash** [mgibeau/gitlab-npm-audit-parser#2]
Hey @mgibeau - I noticed Group Level Security Dashboards are not supported with this module. I'm taking a look at the generated json from the normal `dependency_scanning` job in gitlab and I see some differences in how the json is structured. One major thing I noticed is that there is a `version` key top level and it seems all the vulnerabilities are in a `vulnerabilities` key top level.

**Comment by mgibeau** [comment]
Yup, quite possible, I haven't had the chance to test this out with a more recent version of GitLab enterprise and since this was pretty much a reverse-engineering effort, I suspect it needs adjustments. I'd be happy to accept a merge request if you're up for it!

**Comment by nikmash** [comment]
@mgibeau do you mind publishing the new version? I forgot to update the package-lock.json file sorry!

**Comment by mgibeau** [comment]
Oops my bad, done now! Thanks again!
